# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JET-4FYg13M8snpStCXvFjl7pLxf5YJ
"""

# 1. Upload Data File in Colab
from google.colab import files
uploaded = files.upload()

# sentiment_analysis.ipynb

import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob

# Load reviews
df = pd.read_csv("reviews.csv")

# Clean text (basic cleaning)
df['cleaned'] = df['review_text'].str.lower().str.replace('[^\w\s]','', regex=True)

# Calculate sentiment polarity
df['polarity'] = df['cleaned'].apply(lambda text: TextBlob(text).sentiment.polarity)

# Classify as Positive, Neutral, Negative
def classify_sentiment(p):
    if p > 0.1:
        return "Positive"
    elif p < -0.1:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['polarity'].apply(classify_sentiment)

# Show summary
print(df[['review_text', 'polarity', 'sentiment']])

# Plot sentiment distribution
df['sentiment'].value_counts().plot(kind='bar', color=['green', 'red', 'gray'])
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.tight_layout()
plt.savefig("sentiment_distribution.png")
plt.show()

